### ISSUE TITLE
Filter for Subtasks with Timer turned on (independent of substask status)

### ISSUE THREAD

**Issue by neiaberau** [creecros/Creecros_Filter_Pack#2]
The Filter works as expected, I can now find all substask as per their status, thanks for you effort, 

In Kanboard  users can also just start/stop the timer without changing the substask status.
A running timer, could also imply an active (or often also forgotten) subtask, even if the subtask status itself is on done or todo status. 

A filter that helps to identify these would also be helpfull (or train the user do not use this 2nd option, then it is not needed ...).

If my interpretation of the data in the database is correct, for a standard kanboard installation, these should be subtaskids without end date in the table "subtask_time_tracking".

**Comment by creecros** [comment]
I actually disabled timers in my production Kanboard, so I am unfamiliar, but I will look into adding this filter for you.

**Comment by creecros** [comment]
Ah, ok, I figured out what you are talking about. I'll take care of it.

**Comment by creecros** [comment]
Master is updated, use `subtask:status:RUNNING` to find running timers, regardless of `STATUS`.

I will update the release and website link, next chance I get.

**Comment by neiaberau** [comment]
for me this is perfect, thank you
