### ISSUE TITLE
Request Filter

### ISSUE THREAD

**Issue by acbird** [creecros/Creecros_Filter_Pack#6]
Hi, 
I'd like to request a filter for your filter pack if that is still possible.  I have a category for "other" stuff, called "_ToDo".  I'd like a filter that excluded that stuff from the board view.
I could do it by making a filter that had every category except this one, so if you're busy then please don't worry.

best wishes, 
Andrew.

**Comment by creecros** [comment]
still need this? sorry, this repo always seems to go ignored. if so, can you provide a little more detail.
