### ISSUE TITLE
me-Keyword in filters

### ISSUE THREAD

**Issue by StepByWeb** [creecros/Creecros_Filter_Pack#8]
Hi,

it whould be really helpful if your filters could be used with Kanboard's me-Keyword, e. g.

`task_subtask_assignee:me`

**Comment by creecros** [comment]
far as i can tell, it does:

https://github.com/creecros/Creecros_Filter_Pack/blob/f9a2721d5d0749634d5691c23d005c9bff93a952/Filter/SubtaskAssignee.php#L124

**Comment by StepByWeb** [comment]
Strange. Doesn't seem to work for me in the following case: 

- I try to filter my project board with the following query

`status:open task_subtask_assignee:me`

- I am assigned to a subtask
- I am not assigned to the task itself

Result: I don't see the task in my board I expect to see.

**Comment by creecros** [comment]
its been so long since I've used kanboard, could be awhile, if ever, that I look into it. I will try and make time.

**Comment by StepByWeb** [comment]
Thank you very much.

**Comment by creecros** [comment]
should be all set now, i never set the "or" criteria for "me" and "nobody".

You will have to use the Master repo, untl I get a chance to update on Kanboard Website.
